sudo: false
dist: trusty

language: rust

cache:
  cargo: true
  apt: true

rust:
  - stable
  - beta
  - nightly

addons:
  apt:
    packages:
      - libcurl4-openssl-dev
      - libelf-dev
      - libdw-dev
      - libprotobuf-dev
      - binutils-dev
      - protobuf-compiler

install:
  - cargo install cargo-travis || echo "Cargo travis is already installed!"
  - export PATH=$HOME/.cargo/bin:$PATH

script:
  - cargo build --all
  - cargo test --all

after_success: |
  if [ "$TRAVIS_RUST_VERSION" == "stable" ]; then
    cargo coveralls --exclude-pattern tests/ --all;
  fi


