sudo: false
dist: trusty

language: rust

cache:
  cargo: true
  apt: true

rust:
  - stable
  - beta
  - nightly

addons:
  apt:
    sources:
    - sourceline: 'ppa:chris-lea/libsodium'
    packages:
      # Cargo coverage dependencies
      - libcurl4-openssl-dev
      - libelf-dev
      - libdw-dev
      - binutils-dev
      # Dependencies for Mjolnir
      - protobuf-compiler
      - libprotobuf-dev
      - libsodium-dev
      - libzmq3-dev
install:
  - cargo install cargo-travis || echo "Cargo travis is already installed!"
  - export PATH=$HOME/.cargo/bin:$PATH

script:
  - cargo build --all
  - cargo test --all

after_success: |
  if [ "$TRAVIS_RUST_VERSION" == "stable" ]; then
    cargo coveralls --exclude-pattern tests/,mjolnir-api/src/agent.rs,mjolnir-api/src/plugin.rs,mjolnir-api/src/mjolnir.rs --all
  fi


