sudo: false
dist: trusty

language: rust

cache:
  cargo: true
  apt: true
  directories:
    - $HOME/lib
    - $HOME/include

rust:
  - stable
  - beta
  - nightly

addons:
  apt:
    sources:
    - sourceline: 'ppa:chris-lea/libsodium'
    packages:
      # Cargo coverage dependencies
      - libcurl4-openssl-dev
      - libelf-dev
      - libdw-dev
      - binutils-dev
      # Dependencies for Mjolnir
      - protobuf-compiler
      - libprotobuf-dev
      - libsodium-dev
      # - libzmq3-dev # can't use trusty's version of zmq because it's too old
install:
  - cargo install cargo-travis || echo "Cargo travis is already installed!"
  - export PATH=$HOME/.cargo/bin:$PATH

before_script: |
  export PATH=$HOME/.local/bin:$PATH &&
  export LIBRARY_PATH=$HOME/lib &&
  export LD_LIBRARY_PATH=$HOME/lib &&
  export PKG_CONFIG_PATH=$HOME/lib/pkgconfig
  if [ ! -d "$HOME/lib" ]; then
    cd /tmp
    curl -sSOL https://github.com/zeromq/libzmq/releases/download/v4.2.0/zeromq-4.2.0.tar.gz
    tar zxf zeromq-4.2.0.tar.gz
    cd zeromq-4.2.0
    ./autogen.sh
    ./configure --prefix=$HOME --with-libsodium
    make -j 2 && make install
    cd $TRAVIS_BUILD_DIR
  fi

stages:
  - name: test
  - name: functional
    if: env(TRAVIS_RUST_VERSION) = stable

jobs:
  include:
    - stage: test
      script: cargo test --all --verbose
    - stage: functional
      script:
        # setup dependencies here to save time on simpler test environments
        # sudo back to ourself to activate lxd group membership
        - sudo add-apt-repository -y ppa:ubuntu-lxc/lxd-stable;
          sudo apt-get -qq update;
          sudo apt-get -y install lxd;
          sudo lxd init --auto;
          sudo usermod -a -G lxd travis;
          sudo su travis -c 'lxc network create lxdbr0';
          sudo su travis -c 'lxc network attach-profile lxdbr0 default eth0';
        - VERBOSE=true tests/run.sh

after_success: |
  if [ "$TRAVIS_RUST_VERSION" == "stable" ]; then
    cargo coveralls --exclude-pattern tests/,mjolnir-api/src/proto/mjolnir.rs,mjolnir-api/src/proto/plugin.rs,mjolnir-api/src/proto/agent.rs  --all
  fi

# Could do this to provide trusty debs

# before_deploy: |
#   test $TRAVIS_TEST_RESULT = 0 \
#   test $TRAVIS_RUST_VERSION = "stable" \
#   test $TRAVIS_TAG \
#   cargo install cargo-deb &&
#   cargo deb

# deploy:
#   provider: releases
#   api_key: "GITHUB OAUTH TOKEN"
#   file: "/target/release/
#   skip_cleanup: true
#   on:
#     tags: true
#     rust: stable