[package]
name = "mjolnir"
version = "0.1.0"
authors = [
    "Chris MacNaughton <chris@centaurisolutions.nl>",
    "Chris Holcombe <xfactor973@gmail.com>",
]
license = "AGPL-3.0"
description = "Mjölnir is a tool to manage large numbers of servers."
homepage = "https://github.com/ChrisMacNaughton/Mjolnir"
repository = "https://github.com/ChrisMacNaughton/Mjolnir.git"

[dependencies]
mjolnir-api = { path = "mjolnir-api"}

[workspace]
members = [ "mjolnir-api", "mjolnird" ]