
[mjolnir]
  config_path = "../examples/configs"
  # Masters have the format $IP:HTTP_PORT:$ZMQ_PORT
  masters = ["127.0.1.1:11011:12011"]
  plugin_path = "../target/debug/examples"

[master]
bind = "0.0.0.0:11011:12011"

[agent]
bind = "0.0.0.0:11012:12012"

[[pipelines]]

  [[pipelines.actions]]
    plugin = "clean_disk"

#   [[pipelines.actions]]
#     plugin = "alert"

  [pipelines.trigger]
    type = "alertmanager"
    name = "full-disk"
