
[mjolnir]
  key_path = "../examples/configs"
  # Masters have the format $IP:HTTP_PORT:$ZMQ_PORT
  masters = ["127.0.1.1:11011:12011"]
  plugin_path = "../target/debug/examples"
  # bind = "127.0.0.1:11011:12011"
  secret = "w[4957ha[ruognqp357gf;eruigap47gfa;IRYEgf0a864fo"

[master]
bind = "0.0.0.0:11011:12011"

[agent]
bind = "0.0.0.0:11012:12012"
key_path  = "/tmp/agent_keys"

[[pipelines]]

  [[pipelines.actions]]
    plugin = "clean_disk"

#   [[pipelines.actions]]
#     plugin = "alert"

  [pipelines.trigger]
    type = "alertmanager"
    name = "full-disk"
