[package]
name = "mjolnird"
version = "0.1.0"
authors = ["Chris MacNaughton <chris@centaurisolutions.nl>"]

[dependencies]
mjolnir = { path = ".."}
clap = "2.26"
hyper = "*"
service-fn = { git = "https://github.com/tokio-rs/service-fn" }