[package]
name = "mjolnird"
version = "0.1.0"
authors = ["Chris MacNaughton <chris@centaurisolutions.nl>"]

[dependencies]
mjolnir-api = { path = "../mjolnir-api" }
mjolnir = { path = ".."}
clap = "2.26"
futures = "0.1.16"
hyper = "0.11.6"
tokio-core = "0.1"
protobuf = "1.4" 