[package]
name = "api"
version = "0.1.0"
authors = [
    "Chris MacNaughton <chris@centaurisolutions.nl>",
]
license = "AGPLv3"
build = "build.rs"

[build-dependencies]
protoc-rust = "*" 
protoc = "*" 

[dependencies]
protobuf = "*" 
